### ISSUE TITLE
No keyboard

### ISSUE THREAD

**Issue by theoqrz** [Sabissimo/AssistantEnabler#1]
I can long press the home button to call the interface and talk to it. The only problem is that I don't have a keyboard to type in. Is this the way that's supposed to be?

**Comment by Maxr1998** [comment]
Yes.

**Comment by theoqrz** [comment]
Ok. So, is this a bug addressed? Because I guess, by the videos on youtube, that the Pixel phones have a keyboard within the assistant

**Comment by Maxr1998** [comment]
Nope, they actually don't. The Google Assistant with keyboard can be found in Google Allo, the messenger.
