### ISSUE TITLE
Cannot disable Assistant from Google app settings

### ISSUE THREAD

**Issue by alice-mkh** [Sabissimo/AssistantEnabler#13]
It seems that if we stop spoofing opa_enabled value in config file, then the Assistant still works, but can be disabled the normal way. In this case, if you try to summon it, it looks like this: 
![screenshot_20170108-012800](https://cloud.githubusercontent.com/assets/1510457/21744960/45b4539e-d542-11e6-8031-15d19f6c60ae.png)
Translation: Google Assistant is disabled. Enable? No | Yes
As you can see, the Assistant is properly disabled in the settings. If I turn it on either via the Yes button, or via settings, it functions normally.
I would do pull request for this, but I haven't properly tested what will happen on a clean install of the module: it's possible that it only allows this because I already had it enabled on this device.
Either way, you might be interested in this.

**Comment by Sabissimo** [comment]
Tested it on clean install of the module, and it does indeed work. Merged it into repo and pushed new version out. Thanks!

P.S.
Можешь писать и по-русски ;-)

**Comment by alice-mkh** [comment]
Хм, ладно. Но вообще я обычно на англоязычных сайтах по-русски не пишу, все-таки тут и другие люди есть. Баг закрываю, раз всё нормально.
