### ISSUE TITLE
Recognize issue

### ISSUE THREAD

**Issue by BrunoTheRed** [Sabissimo/AssistantEnabler#2]
Every time i say" ok google", assistant opens but ask me to set the voice for recognizing and i have to repeat "ok google" 3 times every time...but if i open google assistant holding the home button it works perfectly.

**Comment by ghost** [comment]
Known issue, if you just press "do it later" instead of going through the setup again it'll kick you right on through to the assistant. Kind of defeats the purpose of hands-free activation, I realize, but that's a minor annoyance yet to be overcome at the moment.

**Comment by BrunoTheRed** [comment]
Yeah i've noticed that, but it's still annoying so it's better to open google assitant using the home button, which is not bugged.

**Comment by Zahweh** [comment]
Ditto

**Comment by Sabissimo** [comment]
Fixed as version 3.0
