### ISSUE TITLE
Support Google 6.9.x

### ISSUE THREAD

**Issue by alice-mkh** [Sabissimo/AssistantEnabler#6]
Google 6.9.31.21 has been released on beta channel. Assistant Enabler does not work with it. Either the obfuscation has changed or the module blacklists this version. Xposed log does not contain anything unusual.

**Comment by Sabissimo** [comment]
Obfuscation changes with every major version update, already on it, will add support in few hours

**Comment by alice-mkh** [comment]
Ok, thanks.

**Comment by alice-mkh** [comment]
It works
