### ISSUE TITLE
For Android 7.

### ISSUE THREAD

**Issue by Subinsmani** [Sabissimo/AssistantEnabler#7]
Hai i have succesfully ported pixel nav button to our system ui, Sp i want to ask u that can u give me guide to enable to our rom, as of u know that till now xposed module is not working on android 7.1 so please give me any guide to enable this,, :)

**Comment by Sabissimo** [comment]
Hi
I think this thread http://forum.xda-developers.com/android/software/guide-how-to-enable-google-assistant-t3477879 is what you're looking for
It doesn't enable ok google though :(

**Comment by Subinsmani** [comment]
Still we are using this,,,
But i want to port ur module to our rom,, is there any way to do it,,,
http://forum.xda-developers.com/2015-moto-g/general/cm14-1-pixel-navigation-bar-home-button-t3505470
This is my forum,, :)
