### ISSUE TITLE
App doesn't work on Google 6.9+

### ISSUE THREAD

**Issue by NovaViper** [Sabissimo/AssistantEnabler#8]
Hey, the module stopped working when the Google App updated to the latest (the app autoupdated to 6.9.37 and tried rolling back to 6.8.36). The app started working again upong rolling back to 6.8.23, will there be a patch for 6.9.+?

**Comment by Sabissimo** [comment]
It does work, however there was a bugged version of the module published once, so there's a chance you have it, try reinstalling module, should fix your problem

**Comment by NovaViper** [comment]
That worked! I updated the Google app and reinstalled the latest version Assistant Enabler and it started working again. Thanks!
